### ISSUE TITLE
Possible to publish the current development branch to maven?

### ISSUE THREAD

**Issue by thoatbk** [SnowdreamFramework/android-autoupdater#13]
Hey,
would it be possible for you to publish the current development branch to maven?
the 1.0 version is kinda outdated and makes troubles with newer android projects and compiling itself and publishing to a local maven repo is cumbersome as the used libraries are also outdated (like the downloader lib).

**Comment by snowdream** [comment]
what is the problem?

**Comment by thoatbk** [comment]
After adding it to newer projects you get errors on compilation like this:

Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.


This seems to be caused after by appcompat stuff -> https://code.google.com/p/android/issues/detail?id=183149

I am on Android 5.0 SDK btw (Build tools 21.1.2 + API 21)
with
